
image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
- port: 3306
  onOpen: ignore

tasks:
- name: Terminal
  command: >
    curl https://rclone.org/install.sh | sudo bash;
    composer install;
    bash scripts/secrets.sh;
    mkdir upload/uploads;
    gp await-port 3306 &&
    mysql -e "CREATE DATABASE iclip;";
    mysql < scripts/db.sql;
- name: Apache
  command: >
    sudo cp apache.conf /etc/apache2/apache2.conf
    sudo service apache2 restart &&
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client