image:
  file: .gitpod.dockerfile
  context: apache
ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    echo "";
    mysql -e "CREATE DATABASE iclip; USE iclip;"
    mysql < scripts/db.sql
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log