name: GitPod deploy PR comment

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]

jobs:
  comment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: You can setup this branch on Gitpod and preview it by clicking [here](https://gitpod.io/#https://github.com/aperta-principium/Interclip/pull/${{ github.event.number }}).
