name: Remotely deploy code to the production server
on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Git pull on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /var/www/html && sudo git pull --all && sudo composer install
        
  purge-cache:
    name: Purge Cloudflare cache
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Purge cache
    - run: git diff --name-only HEAD^ > diff.txt
    - run: FILES=$(python3 scripts/arrayify.py)
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        PURGE_URLS: ${{ $FILES }}
