name: Remotely deploy code to the production server
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Git pull on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /var/www/html && sudo git pull --all && sudo composer install
